### ISSUE TITLE
[BUG] UI not opening

### ISSUE THREAD

**Issue by izMystic** [Mojito-Fivem/mojito_pdm#11]
whenever the resource starts it throws 
`TypeError: Cannot read property 'map' of null (@mojito_pdm/ui/build/static/js/2.e4f98f24.chunk.js:2)`
which makes it unable to show the UI when selecting Open Catalogue

Using lastest release 2.5.0
All up-to date default QBCore files

**Comment by LiamDormon** [comment]
i forgor 💀 to add the cars.json to the CI script, fixed in v2.5.1
