### ISSUE TITLE
Car won't save in my garage nor will it give me keys

### ISSUE THREAD

**Issue by unsafeknave** [Mojito-Fivem/mojito_pdm#15]
When trying to buy a car it will take the money but will not give me keys or save to my garage.
https://i.imgur.com/NYB0Bpa.jpeg
https://i.imgur.com/PHgTbzb.jpeg

**Comment by LiamDormon** [comment]
Use legacy fuel or change the export

**Comment by unsafeknave** [comment]
> Use legacy fuel or change the export

I could be stupid but i'm not seeing where to change the export

**Comment by LiamDormon** [comment]
https://github.com/Mojito-Fivem/mojito_pdm/blob/900b80e29b7795bbe84db7149075051e8bd55494/resources/client/client.ts#L149

**Comment by unsafeknave** [comment]
> https://github.com/Mojito-Fivem/mojito_pdm/blob/900b80e29b7795bbe84db7149075051e8bd55494/resources/client/client.ts#L149

So i've been trying to solve this issue and I have come across the fact that the source code doesn't work but the released version does. In the released version there is no client.ts. I would use the source code version but it doesn't work on my QB server

**Comment by LiamDormon** [comment]
> > https://github.com/Mojito-Fivem/mojito_pdm/blob/900b80e29b7795bbe84db7149075051e8bd55494/resources/client/client.ts#L149
> 
> So i've been trying to solve this issue and I have come across the fact that the source code doesn't work but the released version does. In the released version there is no client.ts. I would use the source code version but it doesn't work on my QB server

This is typescript, you need to compile it. Release version is just the github bot automatically compiling the code when I push a new version tag.

**Comment by unsafeknave** [comment]
> > > https://github.com/Mojito-Fivem/mojito_pdm/blob/900b80e29b7795bbe84db7149075051e8bd55494/resources/client/client.ts#L149
> > 
> > 
> > So i've been trying to solve this issue and I have come across the fact that the source code doesn't work but the released version does. In the released version there is no client.ts. I would use the source code version but it doesn't work on my QB server
> 
> This is typescript, you need to compile it. Release version is just the github bot automatically compiling the code when I push a new version tag.

sadly i'm not fluent in TS so i'm not sure how to compile the script myself. I apologize for bothering you
