### ISSUE TITLE
Cannot change Vehicle color in bennys after selecting it While Buying the Vehicle in PDM

### ISSUE THREAD

**Issue by Tamer173** [Mojito-Fivem/mojito_pdm#19]
**I have uploaded the video which shows that after buing a vehicle with custom color we cannnot change its color in bennys!**

![image](https://user-images.githubusercontent.com/105336574/182773800-949b6c95-bee3-4fef-ba68-55e3c94c6739.png)

**_The above are my settings_**

Here is the Video

**https://streamable.com/drsxa0**

**Comment by LiamDormon** [comment]
This is a known issue that occurs when the 'bennys script' isn't working correctly and assumes a custom colour paint job is a regular indexed paint job and tries to update it that way rather than handle 'crew paint' or whatever it's called in GTA

**Comment by Tamer173** [comment]
> This is a known issue that occurs when the 'bennys script' isn't working correctly and assumes a custom colour paint job is a regular indexed paint job and tries to update it that way rather than handle 'crew paint' or whatever it's called in GTA

Then is there any solution to fix this?
