### ISSUE TITLE
Cars.json is included in build

### ISSUE THREAD

**Issue by soodohcool** [Mojito-Fivem/mojito_pdm#4]
Having Cars.json included in build prevents user from editing the vehicles in the catalog unless they build from source. Inconsistencies can arise between PDM Catalog and Shared lua.

**Comment by Mojito-Fivem** [comment]
If you have a good workaround feel free to PR it but this is the highest performing method I have tried, by importing  the data directly to the UI. When I tried having the file included in the bundle and fetching the data the UI became slow and unresponsive with large datasets.

**Comment by Mojito-Fivem** [comment]
Created an experimental branch with runtime loaded config, initial performance is a bit slower to load but otherwise behaves as normal https://github.com/Mojito-Fivem/mojito_pdm/tree/feature/runtime-config

**Comment by Mojito-Fivem** [comment]
Merged #9 with version 2.5.0
