### ISSUE TITLE
Menu does not open

### ISSUE THREAD

**Issue by p3dr0jsm2** [Mojito-Fivem/mojito_pdm#5]
Hi everyone, I'm not able to open the vehicleshop menu... I put it in qb-target and cd_drawtextui but none of them works. Anyone have an idea what it could be? PS: It doesn't give any error
Thanks in advance!

**Comment by Mojito-Fivem** [comment]
No repro, no showing what you've already done? Did you even download the release or the source code

**Comment by p3dr0jsm2** [comment]
Sorry, had an old version of the script. I'm sorry again. I just have one more doubt, how do I put addon cars? It's just that I tried to change it on shared.lua but it didn't put it in the catalog.

**Comment by Mojito-Fivem** [comment]
It doesn't pull data from there
