### ISSUE TITLE
Unable to change the colour

### ISSUE THREAD

**Issue by MagicHeroZ** [Mojito-Fivem/mojito_pdm#6]
Not sure if its just my case, but after selecting a colour, and purchasing the vehicle, you can no longer change the colour of that vehicle.
Seems to be happening with all of the colours. 

Using vMenu and qb-customs to modify the cars.

**Comment by Mojito-Fivem** [comment]
These scripts you're using must not be set up to deal with RGB colour (crew paintjobs)

**Comment by MagicHeroZ** [comment]
Makes sense, thank you so much for your answer
