### ISSUE TITLE
In Game the menu doesnt show

### ISSUE THREAD

**Issue by madalex24** [Mojito-Fivem/mojito_pdm#8]
Ive looked in the fx manifest lua file the files to be loaded are not in the order they in the file 

![pdm files](https://user-images.githubusercontent.com/91700454/156247794-9b8f5a37-6261-470d-a8b0-750d7a3d494b.png)
![pdm files1](https://user-images.githubusercontent.com/91700454/156247797-793adaff-2132-483b-84f1-5d5cff4b6509.png)
![pdm files2](https://user-images.githubusercontent.com/91700454/156247799-e2fea6cc-4425-4aa1-9278-934e83cc9439.png)
![pdm files3](https://user-images.githubusercontent.com/91700454/156247800-7b202b3b-8241-432b-97f1-fdcf8aa40791.png)

**Comment by Mojito-Fivem** [comment]
You've downloaded the source code, either build the resource or download the built version. Renaming a typescript file to .js will not make it run
